# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracking/v2/service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tracking/v2/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import messages_pb2 as tracking_dot_v2_dot_messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19tracking/v2/service.proto\x12\x0btracking.v2\x1a\x1atracking/v2/messages.proto\"I\n\x0cMeshEnvelope\x12\x12\n\ndevice_uid\x18\x01 \x01(\t\x12%\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x16.tracking.v2.ServerMsg\"\x15\n\x07MeshAck\x12\n\n\x02ok\x18\x01 \x01(\x08\"R\n\x0eHandOffRequest\x12\r\n\x05shard\x18\x01 \x01(\r\x12\r\n\x05\x65poch\x18\x02 \x01(\x04\x12\x11\n\tfrom_node\x18\x03 \x01(\t\x12\x0f\n\x07to_node\x18\x04 \x01(\t\".\n\x0fHandOffResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2I\n\x08Tracking\x12=\n\x07Session\x12\x16.tracking.v2.ClientMsg\x1a\x16.tracking.v2.ServerMsg(\x01\x30\x01\x32\x8c\x01\n\x04Mesh\x12>\n\x07\x46orward\x12\x19.tracking.v2.MeshEnvelope\x1a\x14.tracking.v2.MeshAck(\x01\x30\x01\x12\x44\n\x07HandOff\x12\x1b.tracking.v2.HandOffRequest\x1a\x1c.tracking.v2.HandOffResponseB2Z0github.com/pickpoint/go-sdk/tracking/v2;trackingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracking.v2.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pickpoint/go-sdk/tracking/v2;tracking'
  _globals['_MESHENVELOPE']._serialized_start=70
  _globals['_MESHENVELOPE']._serialized_end=143
  _globals['_MESHACK']._serialized_start=145
  _globals['_MESHACK']._serialized_end=166
  _globals['_HANDOFFREQUEST']._serialized_start=168
  _globals['_HANDOFFREQUEST']._serialized_end=250
  _globals['_HANDOFFRESPONSE']._serialized_start=252
  _globals['_HANDOFFRESPONSE']._serialized_end=298
  _globals['_TRACKING']._serialized_start=300
  _globals['_TRACKING']._serialized_end=373
  _globals['_MESH']._serialized_start=376
  _globals['_MESH']._serialized_end=516
# @@protoc_insertion_point(module_scope)
