# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import messages_pb2 as tracking_dot_v2_dot_messages__pb2
from . import service_pb2 as tracking_dot_v2_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tracking/v2/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackingStub:
    """Public bidi session (mounted under /v2/tracking/grpc).
    Named Session (not Connect) to avoid clashing with tonic client's connect().
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/tracking.v2.Tracking/Session',
                request_serializer=tracking_dot_v2_dot_messages__pb2.ClientMsg.SerializeToString,
                response_deserializer=tracking_dot_v2_dot_messages__pb2.ServerMsg.FromString,
                _registered_method=True)


class TrackingServicer:
    """Public bidi session (mounted under /v2/tracking/grpc).
    Named Session (not Connect) to avoid clashing with tonic client's connect().
    """

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=tracking_dot_v2_dot_messages__pb2.ClientMsg.FromString,
                    response_serializer=tracking_dot_v2_dot_messages__pb2.ServerMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.v2.Tracking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.v2.Tracking', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tracking:
    """Public bidi session (mounted under /v2/tracking/grpc).
    Named Session (not Connect) to avoid clashing with tonic client's connect().
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tracking.v2.Tracking/Session',
            tracking_dot_v2_dot_messages__pb2.ClientMsg.SerializeToString,
            tracking_dot_v2_dot_messages__pb2.ServerMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MeshStub:
    """Inter-node mesh (MESH_ADDR only, not on public Ingress).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forward = channel.stream_stream(
                '/tracking.v2.Mesh/Forward',
                request_serializer=tracking_dot_v2_dot_service__pb2.MeshEnvelope.SerializeToString,
                response_deserializer=tracking_dot_v2_dot_service__pb2.MeshAck.FromString,
                _registered_method=True)
        self.HandOff = channel.unary_unary(
                '/tracking.v2.Mesh/HandOff',
                request_serializer=tracking_dot_v2_dot_service__pb2.HandOffRequest.SerializeToString,
                response_deserializer=tracking_dot_v2_dot_service__pb2.HandOffResponse.FromString,
                _registered_method=True)


class MeshServicer:
    """Inter-node mesh (MESH_ADDR only, not on public Ingress).
    """

    def Forward(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forward': grpc.stream_stream_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=tracking_dot_v2_dot_service__pb2.MeshEnvelope.FromString,
                    response_serializer=tracking_dot_v2_dot_service__pb2.MeshAck.SerializeToString,
            ),
            'HandOff': grpc.unary_unary_rpc_method_handler(
                    servicer.HandOff,
                    request_deserializer=tracking_dot_v2_dot_service__pb2.HandOffRequest.FromString,
                    response_serializer=tracking_dot_v2_dot_service__pb2.HandOffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.v2.Mesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.v2.Mesh', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mesh:
    """Inter-node mesh (MESH_ADDR only, not on public Ingress).
    """

    @staticmethod
    def Forward(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tracking.v2.Mesh/Forward',
            tracking_dot_v2_dot_service__pb2.MeshEnvelope.SerializeToString,
            tracking_dot_v2_dot_service__pb2.MeshAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.v2.Mesh/HandOff',
            tracking_dot_v2_dot_service__pb2.HandOffRequest.SerializeToString,
            tracking_dot_v2_dot_service__pb2.HandOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
