"""Realtime tracking (binary WebSocket, tracking.v2)."""

from .backoff import BackoffState, new_backoff, next_delay, reset_backoff
from .client import (
    MAX_EVENT_BYTES,
    MAX_EVENT_HZ,
    MAX_PUBLISH_HZ,
    MIN_EVENT_INTERVAL,
    MIN_PUBLISH_INTERVAL,
    Client,
    connect,
)
from .codec import (
    client_resume,
    decode_client_msg,
    decode_server_msg,
    encode_client_msg,
    encode_loc_frames,
    encode_server_msg,
    stamp_lat_lng,
)
from .errors import Error, is_auth_error, is_fatal_resume_error, is_retry_resume_error, new_error
from .filter import NoiseFilter
from .queue import OfflineQueue, QueuedPoint
from .rate import MIN_PUBLISH_INTERVAL_MS, can_accept_publish, next_publish_allowed_at
from .types import (
    PROTOCOL_VERSION,
    SUBPROTOCOL,
    Ack,
    ClientMsg,
    Command,
    CommandAckStatus,
    Config,
    ConnectionState,
    DeviceAuth,
    ErrorCode,
    LatLng,
    ListenerAuth,
    Loc,
    RefreshAuthFn,
    ServerMsg,
    Transport,
)
from .url import build_ws_url

__all__ = [
    "Ack",
    "BackoffState",
    "Client",
    "ClientMsg",
    "Command",
    "CommandAckStatus",
    "Config",
    "ConnectionState",
    "DeviceAuth",
    "Error",
    "ErrorCode",
    "LatLng",
    "ListenerAuth",
    "Loc",
    "MAX_EVENT_BYTES",
    "MAX_EVENT_HZ",
    "MAX_PUBLISH_HZ",
    "MIN_EVENT_INTERVAL",
    "MIN_PUBLISH_INTERVAL",
    "MIN_PUBLISH_INTERVAL_MS",
    "NoiseFilter",
    "OfflineQueue",
    "PROTOCOL_VERSION",
    "QueuedPoint",
    "RefreshAuthFn",
    "SUBPROTOCOL",
    "ServerMsg",
    "Transport",
    "build_ws_url",
    "can_accept_publish",
    "client_resume",
    "connect",
    "decode_client_msg",
    "decode_server_msg",
    "encode_client_msg",
    "encode_loc_frames",
    "encode_server_msg",
    "is_auth_error",
    "is_fatal_resume_error",
    "is_retry_resume_error",
    "new_backoff",
    "new_error",
    "next_delay",
    "next_publish_allowed_at",
    "reset_backoff",
    "stamp_lat_lng",
]
